### ISSUE TITLE
[please add] Tomb Many Graves 2

### ISSUE THREAD

**Issue by Tenmaver** [kreezxil/Svet-Draku#15]
# Mod Nominated for Adding*
Mod Name: Tomb Many Graves 2
Mod Link: https://www.curseforge.com/minecraft/mc-mods/tomb-many-graves-2

# Reason for Nomination

Reason: a very nice mod for grave when you die, so you dont have all your stuff on the ground.

**Comment by kreezxil** [comment]
Grave mods will never enter the versions I maintain, they can be added by
their respective server owners, but I will not add them. I had them before
and players kept telling me the pack was too easy, that everything was too
easy.

turned out because of gravestones they never lost anything, there was never
a sense of loss. removing the gravestone mods fixed that issue. Now there
is a great sense of loss.
