### ISSUE TITLE
[please add] Mystical Agriculture

### ISSUE THREAD

**Issue by Tenmaver** [kreezxil/Svet-Draku#7]
# Mod Nominated for Adding*
Mod Name: Mystical Agriculture 
Mod Link: https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture

# Reason for Nomination

Reason: Nice touch to farming, magic and crops in one mod. Ability to farm what you actually want.

**Comment by kreezxil** [comment]
actually there is a glaring problem with this mod. Growth Accelerators,
technically easy to make and we had a player make 1500 of them in the
course of 2 days start to finish from scratch. The server came to a
screeching halt. The mod was great up until that point. As I recall I had
to remove the recipe because there was no way to remove the blocks. I could
config them tick at a different rate, but that was no good, 1500
accelerators is still 1500 accelerators.

Remember the player needs to be hunting dragons, that's the goal of the
pack. Not making all the inventory in the game easily and vast amounts just
because you can.
